In [3]:
import pandas as pd
import math

In [2]:
#df=pd.read_excel("MOQ_Output_V1.xlsx")
master = pd.read_excel('master_output.xlsx')

In [4]:
master.head()

,Plant,Billing Date,Sales Document,Document type,Sold-To Party,Customer Name,Billing Amount(inc Tax),Distribution Channel,Reference No,Material Description,...,Old crate,Remarks,Large_Crates,Medium_Crates,Small_Crates,Old_Crates,Large_MOD,Medium_MOD,Small_MOD,Old_MOD
0,1009,2023-03-01,302385859,ZDOM,1000024,CFB Foods Private Limited,85.0,52,902168592,BASIL,...,5,CC Articles,0.20,0.5,1.0,0.20,0,0,1,0
1,1009,2023-03-01,302386046,ZDOM,1000024,CFB Foods Private Limited,85.0,52,902168644,BASIL,...,5,CC Articles,0.20,0.5,1.0,0.20,0,0,1,0
2,1009,2023-03-01,302386037,ZDOM,1000024,CFB Foods Private Limited,85.0,52,902168645,BASIL,...,5,CC Articles,0.20,0.5,1.0,0.20,0,0,1,0
3,1009,2023-03-01,302385770,ZDOM,1015437,JONAHS BISTRO VR MALL,115.0,51,902168671,BASIL,...,5,CC Articles,0.20,0.5,1.0,0.20,0,0,1,0
4,1000,2023-03-02,302389758,ZDOM,1607953,Gopizza India Pvt Ltd- Orion Mall,44.0,51,902173557,BASIL,...,5,CC Articles,0.04,0.1,0.2,0.04,1,0,0,1

In [5]:
master["Medium"].fillna(0, inplace=True)

In [6]:
master["Medium"].unique()

array([ 2.,  3.,  5., 10.,  8.,  0.,  4.])

In [7]:
master["Small"].fillna(0, inplace=True)

In [8]:
master["Small"].unique()

array([1., 0., 2., 5., 3., 4.])

In [9]:
#def small_crates(so_quantity, small, medium, large):
#    remainder = so_quantity % large
#    if (remainder <= small and remainder > 0) :
#        return 1
#    else:
#        return 0

In [10]:
#def medium_crates(so_quantity, small, medium,large):
#    if (so_quantity % large) > small and (so_quantity % large) <= (medium):
#        return 1
#    else:
#        return 0

In [11]:
#def large_crate(so_quantity,small,medium,large):
#    if (so_quantity>medium) & (so_quantity<=large):
#        return 1
#    elif so_quantity>large:
#        return so_quantity // large
#    else:
#        return 0

In [12]:
def wasted(so_quantity, size):
    if size==0:
        return 100
    a=so_quantity%size
    if a==0:
        return a
    else:
        return size-a

In [13]:
math.ceil(125/10)

13

In [14]:
def crates_used(so_quantity, size):
    if size==0:
        return 100
    if size==0:
        return 0
    return math.ceil(so_quantity/size)

In [15]:
crates_used(25,10)

3

In [16]:
#wasted(quantity,carte size)

In [17]:
master["Small_wasted_volume"] = master.apply(lambda row: wasted(row["SO Quantity"], row["Small"]), axis=1)
master["Medium_wasted_volume"] = master.apply(lambda row: wasted(row["SO Quantity"], row["Medium"] ), axis=1)
master["Large_wasted_volume"] = master.apply(lambda row: wasted(row["SO Quantity"], row["Large"]), axis=1)

In [18]:
master["Small_crates_used"] = master.apply(lambda row: crates_used(row["SO Quantity"], row["Small"]), axis=1)
master["Medium_crates_used"] = master.apply(lambda row: crates_used(row["SO Quantity"], row["Medium"] ), axis=1)
master["Large_crates_used"] = master.apply(lambda row: crates_used(row["SO Quantity"], row["Large"]), axis=1)

master["old_crates_used"] = master.apply(lambda row: crates_used(row["SO Quantity"], row["Old crate"]), axis=1)

In [19]:
master["Small_crates_used"] = master["Small_crates_used"] - master["old_crates_used"]
master["Medium_crates_used"] = master["Medium_crates_used"] - master["old_crates_used"]
master["Large_crates_used"] = master["Large_crates_used"] - master["old_crates_used"]

In [20]:
# master.to_excel('naveen.xlsx', index=False)

In [21]:
# Assuming you have a DataFrame called "df" with a column "Material Description" and columns for "Large Crates", "Medium Crates", and "Small Crates"

# Group the data by "Material Description" and calculate the sum of each crate type
crate_sums = master.groupby("Material Description")["Small_wasted_volume", "Medium_wasted_volume", "Large_wasted_volume","Small_crates_used","Medium_crates_used","Large_crates_used","old_crates_used"].sum()
crate_sums = crate_sums.reset_index()
crate_sums

C:\Users\naveen.ganesh\AppData\Local\Temp\ipykernel_6576\3738768988.py:4: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  crate_sums = master.groupby("Material Description")["Small_wasted_volume", "Medium_wasted_volume", "Large_wasted_volume","Small_crates_used","Medium_crates_used","Large_crates_used","old_crates_used"].sum()

,Material Description,Small_wasted_volume,Medium_wasted_volume,Large_wasted_volume,Small_crates_used,Medium_crates_used,Large_crates_used,old_crates_used
0,ASH GOURD,269000.0,269000.0,7154.0,263608,263608,0,5392
1,ASPARAGUS,20.0,40.0,80.0,0,0,0,20
2,BABY POTATO,162.0,437.0,997.0,1,0,0,56
3,BANANA RAW,1455.0,4426.0,12066.0,306,119,0,1647
4,BASIL,15.0,159.0,604.0,7,1,0,149
...,...,...,...,...,...,...,...,...
57,TOMATO HYBRID ECONOMY,481.0,2001.0,7561.0,708,152,0,708
58,TOMATO HYBRID PREMIUM,0.0,5.0,165.0,1029,338,0,354
59,YAM,29000.0,400.0,1300.0,28696,124,0,304
60,ZUCCHINI GREEN,551.0,1327.0,2685.0,0,0,0,194
61,ZUCCHINI YELLOW,475.0,1139.0,2301.0,0,0,0,166

In [22]:
def w2c(wasted_volume, crate_values):
    output = wasted_volume.copy()  # Create a copy of the series to store the output values
    
    for i in range(len(wasted_volume)):
        if crate_values.iloc[i] == 0:
            output.iloc[i] = wasted_volume.iloc[i]
        else:
            output.iloc[i] = wasted_volume.iloc[i] / crate_values.iloc[i]
    
    return output

In [23]:
crate_values = pd.read_excel('crate_values.xlsx')

In [24]:
crate_values["MediumCrate"]=crate_values["MediumCrate"].replace('(blank)',0)

In [25]:
crate_values["SmallCrate"]=crate_values["SmallCrate"].replace('(blank)',0)

In [26]:
crate_values["MediumCrate"].unique()

array([ 0,  3, 10,  5,  2,  8,  4], dtype=int64)

In [27]:
crate_values["SmallCrate"].unique()

array([0, 2, 5, 3, 1, 4], dtype=int64)

In [28]:

crate_sums = pd.merge(crate_values, crate_sums, on="Material Description")

In [29]:
crate_sums["Small_wasted_volume"] = w2c(crate_sums["Small_wasted_volume"], crate_sums["SmallCrate"])
crate_sums["Medium_wasted_volume"] = w2c(crate_sums["Medium_wasted_volume"], crate_sums["MediumCrate"])
crate_sums["Large_wasted_volume"] = w2c(crate_sums["Large_wasted_volume"], crate_sums["LargeCrate"])

In [30]:
#crate_sums = master.groupby("Material Description")["Large Crates", "Medium Crates", "Small Crates"].sum()

# Reset the index to make "Material Description" a column
#crate_sums = crate_sums.reset_index()
#crate_sums

In [31]:
#master["old_crates_used"] = master.apply(lambda row: crates_used(row["SO Quantity"], row["Old crate"]), axis=1)
#crate_sums = master.groupby("Material Description")["old_crates_used"].sum()
#crate_sums = crate_sums.reset_index()

In [32]:
# Calculate the percentages for wasted volumes
#total_volume = crate_sums['Small_wasted_volume'] + crate_sums['Medium_wasted_volume'] + crate_sums['Large_wasted_volume']
#crate_sums['Small_wasted_percentage'] = (crate_sums['Small_wasted_volume'] / total_volume) * 100
#crate_sums['Medium_wasted_percentage'] = (crate_sums['Medium_wasted_volume'] / total_volume) * 100
#crate_sums['Large_wasted_percentage'] = (crate_sums['Large_wasted_volume'] / total_volume) * 100

# Calculate the percentages for crate usage
#total_crates = crate_sums['Small_crates_used'] + crate_sums['Medium_crates_used'] + crate_sums['Large_crates_used']
#crate_sums['Small_crates_percentage'] = (crate_sums['Small_crates_used'] / total_crates) * 100
#crate_sums['Medium_crates_percentage'] = (crate_sums['Medium_crates_used'] / total_crates) * 100
#crate_sums['Large_crates_percentage'] = (crate_sums['Large_crates_used'] / total_crates) * 100

In [33]:
crate_sums

,Material Description,LargeCrate,MediumCrate,SmallCrate,Small_wasted_volume,Medium_wasted_volume,Large_wasted_volume,Small_crates_used,Medium_crates_used,Large_crates_used,old_crates_used
0,ASH GOURD,10,0,0,269000.00,269000.000000,715.40,263608,263608,0,5392
1,ASPARAGUS,5,3,2,10.00,13.333333,16.00,0,0,0,20
2,BABY POTATO,20,10,5,32.40,43.700000,49.85,1,0,0,56
3,BANANA RAW,10,5,3,485.00,885.200000,1206.60,306,119,0,1647
4,BASIL,5,2,1,15.00,79.500000,120.80,7,1,0,149
...,...,...,...,...,...,...,...,...,...,...,...
57,TOMATO HYBRID ECONOMY,20,10,5,96.20,200.100000,378.05,708,152,0,708
58,TOMATO HYBRID PREMIUM,20,10,5,0.00,0.500000,8.25,1029,338,0,354
59,YAM,10,5,0,29000.00,80.000000,130.00,28696,124,0,304
60,ZUCCHINI GREEN,15,8,4,137.75,165.875000,179.00,0,0,0,194
61,ZUCCHINI YELLOW,15,8,4,118.75,142.375000,153.40,0,0,0,166

In [34]:
# Calculate the cost for wasted volumes 
crate_sums['Small_wasted_cost']=crate_sums['Small_wasted_volume'] * 6.67
crate_sums['Medium_wasted_cost']=crate_sums['Medium_wasted_volume'] * 9.39
crate_sums['Large_wasted_cost']=crate_sums['Large_wasted_volume'] * 12.06
# Calculate the cost for crate usage
crate_sums['Small_crates_cost'] = crate_sums['Small_crates_used'] * 2.0834
crate_sums['Medium_crates_cost'] = crate_sums['Medium_crates_used'] * 2.0834
crate_sums['Large_crates_cost'] = crate_sums['Large_crates_used'] * 2.0834

In [35]:
crate_sums['Small']=crate_sums['Small_wasted_cost']+crate_sums['Small_crates_cost']
crate_sums['Medium']=crate_sums['Medium_wasted_cost'] + crate_sums['Medium_crates_cost'] 
crate_sums['Large']=crate_sums['Large_wasted_cost']+crate_sums['Large_crates_cost']

In [36]:
crate_sums

,Material Description,LargeCrate,MediumCrate,SmallCrate,Small_wasted_volume,Medium_wasted_volume,Large_wasted_volume,Small_crates_used,Medium_crates_used,Large_crates_used,old_crates_used,Small_wasted_cost,Medium_wasted_cost,Large_wasted_cost,Small_crates_cost,Medium_crates_cost,Large_crates_cost,Small,Medium,Large
0,ASH GOURD,10,0,0,269000.00,269000.000000,715.40,263608,263608,0,5392,1.794230e+06,2.525910e+06,8627.724,549200.9072,549200.9072,0.0,2.343431e+06,3.075111e+06,8627.724
1,ASPARAGUS,5,3,2,10.00,13.333333,16.00,0,0,0,20,6.670000e+01,1.252000e+02,192.960,0.0000,0.0000,0.0,6.670000e+01,1.252000e+02,192.960
2,BABY POTATO,20,10,5,32.40,43.700000,49.85,1,0,0,56,2.161080e+02,4.103430e+02,601.191,2.0834,0.0000,0.0,2.181914e+02,4.103430e+02,601.191
3,BANANA RAW,10,5,3,485.00,885.200000,1206.60,306,119,0,1647,3.234950e+03,8.312028e+03,14551.596,637.5204,247.9246,0.0,3.872470e+03,8.559953e+03,14551.596
4,BASIL,5,2,1,15.00,79.500000,120.80,7,1,0,149,1.000500e+02,7.465050e+02,1456.848,14.5838,2.0834,0.0,1.146338e+02,7.485884e+02,1456.848
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,TOMATO HYBRID ECONOMY,20,10,5,96.20,200.100000,378.05,708,152,0,708,6.416540e+02,1.878939e+03,4559.283,1475.0472,316.6768,0.0,2.116701e+03,2.195616e+03,4559.283
58,TOMATO HYBRID PREMIUM,20,10,5,0.00,0.500000,8.25,1029,338,0,354,0.000000e+00,4.695000e+00,99.495,2143.8186,704.1892,0.0,2.143819e+03,7.088842e+02,99.495
59,YAM,10,5,0,29000.00,80.000000,130.00,28696,124,0,304,1.934300e+05,7.512000e+02,1567.800,59785.2464,258.3416,0.0,2.532152e+05,1.009542e+03,1567.800
60,ZUCCHINI GREEN,15,8,4,137.75,165.875000,179.00,0,0,0,194,9.187925e+02,1.557566e+03,2158.740,0.0000,0.0000,0.0,9.187925e+02,1.557566e+03,2158.740
61,ZUCCHINI YELLOW,15,8,4,118.75,142.375000,153.40,0,0,0,166,7.920625e+02,1.336901e+03,1850.004,0.0000,0.0000,0.0,7.920625e+02,1.336901e+03,1850.004

In [37]:
#crate_sums['Small'] = crate_sums.apply(lambda row: row['Small_wasted_volume'] * row['Small_crates_used'], axis=1)
#crate_sums['Medium'] = crate_sums.apply(lambda row: row['Medium_wasted_volume'] * row['Medium_crates_used'], axis=1)
#crate_sums['Large'] = crate_sums.apply(lambda row: row['Large_wasted_volume'] * row['Large_crates_used'], axis=1)

In [38]:
crate_sums

,Material Description,LargeCrate,MediumCrate,SmallCrate,Small_wasted_volume,Medium_wasted_volume,Large_wasted_volume,Small_crates_used,Medium_crates_used,Large_crates_used,old_crates_used,Small_wasted_cost,Medium_wasted_cost,Large_wasted_cost,Small_crates_cost,Medium_crates_cost,Large_crates_cost,Small,Medium,Large
0,ASH GOURD,10,0,0,269000.00,269000.000000,715.40,263608,263608,0,5392,1.794230e+06,2.525910e+06,8627.724,549200.9072,549200.9072,0.0,2.343431e+06,3.075111e+06,8627.724
1,ASPARAGUS,5,3,2,10.00,13.333333,16.00,0,0,0,20,6.670000e+01,1.252000e+02,192.960,0.0000,0.0000,0.0,6.670000e+01,1.252000e+02,192.960
2,BABY POTATO,20,10,5,32.40,43.700000,49.85,1,0,0,56,2.161080e+02,4.103430e+02,601.191,2.0834,0.0000,0.0,2.181914e+02,4.103430e+02,601.191
3,BANANA RAW,10,5,3,485.00,885.200000,1206.60,306,119,0,1647,3.234950e+03,8.312028e+03,14551.596,637.5204,247.9246,0.0,3.872470e+03,8.559953e+03,14551.596
4,BASIL,5,2,1,15.00,79.500000,120.80,7,1,0,149,1.000500e+02,7.465050e+02,1456.848,14.5838,2.0834,0.0,1.146338e+02,7.485884e+02,1456.848
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,TOMATO HYBRID ECONOMY,20,10,5,96.20,200.100000,378.05,708,152,0,708,6.416540e+02,1.878939e+03,4559.283,1475.0472,316.6768,0.0,2.116701e+03,2.195616e+03,4559.283
58,TOMATO HYBRID PREMIUM,20,10,5,0.00,0.500000,8.25,1029,338,0,354,0.000000e+00,4.695000e+00,99.495,2143.8186,704.1892,0.0,2.143819e+03,7.088842e+02,99.495
59,YAM,10,5,0,29000.00,80.000000,130.00,28696,124,0,304,1.934300e+05,7.512000e+02,1567.800,59785.2464,258.3416,0.0,2.532152e+05,1.009542e+03,1567.800
60,ZUCCHINI GREEN,15,8,4,137.75,165.875000,179.00,0,0,0,194,9.187925e+02,1.557566e+03,2158.740,0.0000,0.0000,0.0,9.187925e+02,1.557566e+03,2158.740
61,ZUCCHINI YELLOW,15,8,4,118.75,142.375000,153.40,0,0,0,166,7.920625e+02,1.336901e+03,1850.004,0.0000,0.0000,0.0,7.920625e+02,1.336901e+03,1850.004

In [39]:
#crate_sums['Max Crate'] = crate_sums.idxmax(axis=1)
# Assuming you have the crate_sums DataFrame with sums of large crates, medium crates, and small crates for each Material Description

# Convert crate sum columns to numeric data type
#crate_sums[["Large Crates", "Medium Crates", "Small Crates"]] = crate_sums[["Large Crates", "Medium Crates", "Small Crates"]].apply(pd.to_numeric)

# Find the crate with the maximum value for each Material Description
crate_sums['Min_Crate'] = crate_sums[["Large" , "Medium", "Small"]].idxmin(axis=1)

crate_sums

,Material Description,LargeCrate,MediumCrate,SmallCrate,Small_wasted_volume,Medium_wasted_volume,Large_wasted_volume,Small_crates_used,Medium_crates_used,Large_crates_used,...,Small_wasted_cost,Medium_wasted_cost,Large_wasted_cost,Small_crates_cost,Medium_crates_cost,Large_crates_cost,Small,Medium,Large,Min_Crate
0,ASH GOURD,10,0,0,269000.00,269000.000000,715.40,263608,263608,0,...,1.794230e+06,2.525910e+06,8627.724,549200.9072,549200.9072,0.0,2.343431e+06,3.075111e+06,8627.724,Large
1,ASPARAGUS,5,3,2,10.00,13.333333,16.00,0,0,0,...,6.670000e+01,1.252000e+02,192.960,0.0000,0.0000,0.0,6.670000e+01,1.252000e+02,192.960,Small
2,BABY POTATO,20,10,5,32.40,43.700000,49.85,1,0,0,...,2.161080e+02,4.103430e+02,601.191,2.0834,0.0000,0.0,2.181914e+02,4.103430e+02,601.191,Small
3,BANANA RAW,10,5,3,485.00,885.200000,1206.60,306,119,0,...,3.234950e+03,8.312028e+03,14551.596,637.5204,247.9246,0.0,3.872470e+03,8.559953e+03,14551.596,Small
4,BASIL,5,2,1,15.00,79.500000,120.80,7,1,0,...,1.000500e+02,7.465050e+02,1456.848,14.5838,2.0834,0.0,1.146338e+02,7.485884e+02,1456.848,Small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,TOMATO HYBRID ECONOMY,20,10,5,96.20,200.100000,378.05,708,152,0,...,6.416540e+02,1.878939e+03,4559.283,1475.0472,316.6768,0.0,2.116701e+03,2.195616e+03,4559.283,Small
58,TOMATO HYBRID PREMIUM,20,10,5,0.00,0.500000,8.25,1029,338,0,...,0.000000e+00,4.695000e+00,99.495,2143.8186,704.1892,0.0,2.143819e+03,7.088842e+02,99.495,Large
59,YAM,10,5,0,29000.00,80.000000,130.00,28696,124,0,...,1.934300e+05,7.512000e+02,1567.800,59785.2464,258.3416,0.0,2.532152e+05,1.009542e+03,1567.800,Medium
60,ZUCCHINI GREEN,15,8,4,137.75,165.875000,179.00,0,0,0,...,9.187925e+02,1.557566e+03,2158.740,0.0000,0.0000,0.0,9.187925e+02,1.557566e+03,2158.740,Small
61,ZUCCHINI YELLOW,15,8,4,118.75,142.375000,153.40,0,0,0,...,7.920625e+02,1.336901e+03,1850.004,0.0000,0.0000,0.0,7.920625e+02,1.336901e+03,1850.004,Small

In [40]:
crate_sums['crate_size'] = ""

for index, row in crate_sums.iterrows():
    material_desc = row['Material Description']
    column_name = row['Min_Crate']
    value = master.loc[master['Material Description'] == material_desc, column_name].iloc[0]
    crate_sums.at[index, 'crate_size'] = value

In [41]:
crate_sums

,Material Description,LargeCrate,MediumCrate,SmallCrate,Small_wasted_volume,Medium_wasted_volume,Large_wasted_volume,Small_crates_used,Medium_crates_used,Large_crates_used,...,Medium_wasted_cost,Large_wasted_cost,Small_crates_cost,Medium_crates_cost,Large_crates_cost,Small,Medium,Large,Min_Crate,crate_size
0,ASH GOURD,10,0,0,269000.00,269000.000000,715.40,263608,263608,0,...,2.525910e+06,8627.724,549200.9072,549200.9072,0.0,2.343431e+06,3.075111e+06,8627.724,Large,10
1,ASPARAGUS,5,3,2,10.00,13.333333,16.00,0,0,0,...,1.252000e+02,192.960,0.0000,0.0000,0.0,6.670000e+01,1.252000e+02,192.960,Small,2.0
2,BABY POTATO,20,10,5,32.40,43.700000,49.85,1,0,0,...,4.103430e+02,601.191,2.0834,0.0000,0.0,2.181914e+02,4.103430e+02,601.191,Small,5.0
3,BANANA RAW,10,5,3,485.00,885.200000,1206.60,306,119,0,...,8.312028e+03,14551.596,637.5204,247.9246,0.0,3.872470e+03,8.559953e+03,14551.596,Small,3.0
4,BASIL,5,2,1,15.00,79.500000,120.80,7,1,0,...,7.465050e+02,1456.848,14.5838,2.0834,0.0,1.146338e+02,7.485884e+02,1456.848,Small,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,TOMATO HYBRID ECONOMY,20,10,5,96.20,200.100000,378.05,708,152,0,...,1.878939e+03,4559.283,1475.0472,316.6768,0.0,2.116701e+03,2.195616e+03,4559.283,Small,5.0
58,TOMATO HYBRID PREMIUM,20,10,5,0.00,0.500000,8.25,1029,338,0,...,4.695000e+00,99.495,2143.8186,704.1892,0.0,2.143819e+03,7.088842e+02,99.495,Large,20
59,YAM,10,5,0,29000.00,80.000000,130.00,28696,124,0,...,7.512000e+02,1567.800,59785.2464,258.3416,0.0,2.532152e+05,1.009542e+03,1567.800,Medium,5.0
60,ZUCCHINI GREEN,15,8,4,137.75,165.875000,179.00,0,0,0,...,1.557566e+03,2158.740,0.0000,0.0000,0.0,9.187925e+02,1.557566e+03,2158.740,Small,4.0
61,ZUCCHINI YELLOW,15,8,4,118.75,142.375000,153.40,0,0,0,...,1.336901e+03,1850.004,0.0000,0.0000,0.0,7.920625e+02,1.336901e+03,1850.004,Small,4.0

In [42]:
crate_sums.to_excel('final_crate1.xlsx', index=False)

In [43]:
crate_sums

,Material Description,LargeCrate,MediumCrate,SmallCrate,Small_wasted_volume,Medium_wasted_volume,Large_wasted_volume,Small_crates_used,Medium_crates_used,Large_crates_used,...,Medium_wasted_cost,Large_wasted_cost,Small_crates_cost,Medium_crates_cost,Large_crates_cost,Small,Medium,Large,Min_Crate,crate_size
0,ASH GOURD,10,0,0,269000.00,269000.000000,715.40,263608,263608,0,...,2.525910e+06,8627.724,549200.9072,549200.9072,0.0,2.343431e+06,3.075111e+06,8627.724,Large,10
1,ASPARAGUS,5,3,2,10.00,13.333333,16.00,0,0,0,...,1.252000e+02,192.960,0.0000,0.0000,0.0,6.670000e+01,1.252000e+02,192.960,Small,2.0
2,BABY POTATO,20,10,5,32.40,43.700000,49.85,1,0,0,...,4.103430e+02,601.191,2.0834,0.0000,0.0,2.181914e+02,4.103430e+02,601.191,Small,5.0
3,BANANA RAW,10,5,3,485.00,885.200000,1206.60,306,119,0,...,8.312028e+03,14551.596,637.5204,247.9246,0.0,3.872470e+03,8.559953e+03,14551.596,Small,3.0
4,BASIL,5,2,1,15.00,79.500000,120.80,7,1,0,...,7.465050e+02,1456.848,14.5838,2.0834,0.0,1.146338e+02,7.485884e+02,1456.848,Small,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,TOMATO HYBRID ECONOMY,20,10,5,96.20,200.100000,378.05,708,152,0,...,1.878939e+03,4559.283,1475.0472,316.6768,0.0,2.116701e+03,2.195616e+03,4559.283,Small,5.0
58,TOMATO HYBRID PREMIUM,20,10,5,0.00,0.500000,8.25,1029,338,0,...,4.695000e+00,99.495,2143.8186,704.1892,0.0,2.143819e+03,7.088842e+02,99.495,Large,20
59,YAM,10,5,0,29000.00,80.000000,130.00,28696,124,0,...,7.512000e+02,1567.800,59785.2464,258.3416,0.0,2.532152e+05,1.009542e+03,1567.800,Medium,5.0
60,ZUCCHINI GREEN,15,8,4,137.75,165.875000,179.00,0,0,0,...,1.557566e+03,2158.740,0.0000,0.0000,0.0,9.187925e+02,1.557566e+03,2158.740,Small,4.0
61,ZUCCHINI YELLOW,15,8,4,118.75,142.375000,153.40,0,0,0,...,1.336901e+03,1850.004,0.0000,0.0000,0.0,7.920625e+02,1.336901e+03,1850.004,Small,4.0

In [44]:
master

,Plant,Billing Date,Sales Document,Document type,Sold-To Party,Customer Name,Billing Amount(inc Tax),Distribution Channel,Reference No,Material Description,...,Medium_MOD,Small_MOD,Old_MOD,Small_wasted_volume,Medium_wasted_volume,Large_wasted_volume,Small_crates_used,Medium_crates_used,Large_crates_used,old_crates_used
0,1009,2023-03-01,302385859,ZDOM,1000024,CFB Foods Private Limited,85.00,52,902168592,BASIL,...,0,1,0,0.0,1.0,4.0,0,0,0,1
1,1009,2023-03-01,302386046,ZDOM,1000024,CFB Foods Private Limited,85.00,52,902168644,BASIL,...,0,1,0,0.0,1.0,4.0,0,0,0,1
2,1009,2023-03-01,302386037,ZDOM,1000024,CFB Foods Private Limited,85.00,52,902168645,BASIL,...,0,1,0,0.0,1.0,4.0,0,0,0,1
3,1009,2023-03-01,302385770,ZDOM,1015437,JONAHS BISTRO VR MALL,115.00,51,902168671,BASIL,...,0,1,0,0.0,1.0,4.0,0,0,0,1
4,1000,2023-03-02,302389758,ZDOM,1607953,Gopizza India Pvt Ltd- Orion Mall,44.00,51,902173557,BASIL,...,0,0,1,0.8,1.8,4.8,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168901,1017,2023-03-31,302487842,ZDOM,1664574,Krishna Maligai,522.26,50,902275163,DEZI FRESH WATERMELON STRIPED MEDIUM,...,1,0,0,100.0,0.0,0.0,99,5,2,1
168902,1017,2023-03-31,302489407,ZDOM,1612676,K. Kannan Malligai,354.53,50,902275268,DEZI FRESH WATERMELON STRIPED MEDIUM,...,1,0,0,100.0,0.0,0.0,99,3,1,1
168903,1017,2023-03-31,302488502,ZDOM,1655992,Ashwin Store,337.52,50,902275270,DEZI FRESH WATERMELON STRIPED MEDIUM,...,1,0,0,100.0,0.0,0.0,99,3,1,1
168904,1017,2023-03-31,302491530,ZDOM,1646492,Shri Annai Store,165.92,50,902275271,DEZI FRESH WATERMELON STRIPED MEDIUM,...,1,0,0,100.0,0.0,0.0,99,1,0,1
168905,1017,2023-03-31,302490756,ZDOM,1662485,LOCAL SALES FS 1017,101.00,50,902277284,DEZI FRESH WATERMELON STRIPED MEDIUM,...,1,0,0,100.0,0.0,0.0,99,1,0,1

In [ ]:
#master.to_excel('master_final.xlsx', index=False)

In [ ]:

print("hi")

In [3]:
v=[]
centroids

In [2]:
len(v)

216000